FROM python:3.8


COPY web /app
COPY .env /.env
WORKDIR /app

RUN pip3 install -U setuptools
RUN apt-get update -y
RUN apt-get install -y libssl-dev libffi-dev 
RUN apt-get install -y libxml2-dev libxslt1-dev zlib1g-dev 
RUN pip3 install -r requirements.txt

CMD ["gunicorn","--reload","--bind","0.0.0.0:8080","--chdir","/app","wsgi:app"]

